export const CATEGORIES_DISPLAY = {
  NGAN_HANG: "Ngân hàng",
  CHUNG_KHOAN: "Chứng khoán",
  THEP: "Thép",
  DAU_KHI: "Dầu khí",
  BAO_HIEM: "Bảo hiểm",
  BAT_DONG_SAN: "Bất động sản",
  BDS_KCN: "BDS - KCN",
  XD_VLXD: "XD - VLXD",
  DAU_TU_CONG: "Đầu tư công",
  CAO_SU: "Cao su",
  DET_MAY: "Dệt may",
  THAN_KHOANG_SAN: "Than - khoáng sản",
  THUY_SAN: "Thuỷ sản",
  THUC_PHAM_XK: "Thực phẩm XK",
  HOA_CHAT_PHAN_BON: "Hoá chất phân bón",
  BLE_CONG_NGHE: "Bán lẻ - Công nghệ",
  CANG_VAN_TAI: "Cảng vận tải",
  DICH_VU: "Dịch vụ",
  DIEN_NANG_LUONG: "Điện năng lượng",
  DTPT: "DTPT",
  DUONG_GO: "DUONG_GO",
  HANG_KHONG_DU_LICH: "Hàng không du lịch",
  NUOC_NHUA: "Nước nhựa",
  SXKD: "SXKD",
  Y_TE_DUOC: "Y tế - dược",
};
